<template><h1 id="业务功能" tabindex="-1"><a class="header-anchor" href="#业务功能" aria-hidden="true">#</a> 业务功能</h1>
<h2 id="表单验证" tabindex="-1"><a class="header-anchor" href="#表单验证" aria-hidden="true">#</a> 表单验证</h2>
<h3 id="设计表单验证逻辑" tabindex="-1"><a class="header-anchor" href="#设计表单验证逻辑" aria-hidden="true">#</a> 设计表单验证逻辑</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> formData <span class="token operator">=</span> <span class="token function">reactive</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">tagName</span><span class="token operator">:</span><span class="token string">''</span><span class="token punctuation">,</span>
  <span class="token literal-property property">emoji</span><span class="token operator">:</span><span class="token string">''</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span> 

<span class="token keyword">const</span> rules <span class="token operator">=</span> <span class="token punctuation">[</span>
  <span class="token punctuation">{</span> <span class="token literal-property property">key</span><span class="token operator">:</span> <span class="token string">'tagName'</span><span class="token punctuation">,</span> <span class="token literal-property property">required</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token literal-property property">message</span><span class="token operator">:</span> <span class="token string">'必填'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span> <span class="token literal-property property">key</span><span class="token operator">:</span> <span class="token string">'tagName'</span><span class="token punctuation">,</span> <span class="token literal-property property">pattern</span><span class="token operator">:</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^.{1,4}$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">,</span> <span class="token literal-property property">message</span><span class="token operator">:</span> <span class="token string">'请填入1~4个字符'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span> <span class="token literal-property property">key</span><span class="token operator">:</span> <span class="token string">'emoji'</span><span class="token punctuation">,</span> <span class="token literal-property property">required</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token literal-property property">message</span><span class="token operator">:</span> <span class="token string">'必填'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
<span class="token comment">// validate 函数需要封装</span>
<span class="token keyword">const</span> errors <span class="token operator">=</span> <span class="token function">validate</span><span class="token punctuation">(</span>formData<span class="token punctuation">,</span> rules<span class="token punctuation">)</span>
<span class="token comment">// 可以得出 errors 的数据结构为</span>
<span class="token comment">// const errors = {</span>
<span class="token comment">//   'tagName': ['错误信息 1', '错误信息 2'],</span>
<span class="token comment">//   'emoji':['错误信息 3', '错误信息 4']</span>
<span class="token comment">// }</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><p>根据 **表单数据 <code>formData</code> 和 验证规则 <code>rules**</code>, <strong>需要封装一个 <code>validate</code> 工具函数</strong>返回其表单验证对应的 <code>errors</code> 错误信息,
然后可以再根据结果 errors 在模板上渲染</p>
<h3 id="实现表单验证函数" tabindex="-1"><a class="header-anchor" href="#实现表单验证函数" aria-hidden="true">#</a> 实现表单验证函数</h3>
<p>utils/validate.ts</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token comment">// 表单数据</span>
<span class="token keyword">export</span> <span class="token keyword">interface</span> <span class="token class-name">FData</span> <span class="token punctuation">{</span>
  <span class="token punctuation">[</span>k<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">]</span><span class="token operator">:</span> <span class="token builtin">string</span> <span class="token operator">|</span> <span class="token builtin">number</span> <span class="token operator">|</span> <span class="token keyword">undefined</span> <span class="token operator">|</span> <span class="token keyword">null</span>
<span class="token punctuation">}</span>
<span class="token comment">// 每个验证规则 Rule 每个规则的 key 必须是 FData 的属性值, 所以这里使用泛型</span>
<span class="token keyword">export</span> <span class="token keyword">interface</span> <span class="token class-name">Rule<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span></span>  <span class="token punctuation">{</span>
  key<span class="token operator">:</span> <span class="token keyword">keyof</span> <span class="token constant">T</span>
  message<span class="token operator">:</span> <span class="token builtin">string</span>
  required<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">boolean</span>
  pattern<span class="token operator">?</span><span class="token operator">:</span> RegExp
<span class="token punctuation">}</span> 
<span class="token comment">// 验证规则 Rules</span>
<span class="token keyword">export</span> <span class="token keyword">type</span> <span class="token class-name">Rules<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span></span> <span class="token operator">=</span> Rule<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span><span class="token punctuation">[</span><span class="token punctuation">]</span>

<span class="token keyword">export</span> <span class="token keyword">const</span> validate <span class="token operator">=</span> <span class="token operator">&lt;</span><span class="token constant">T</span> <span class="token keyword">extends</span> <span class="token class-name">FData</span><span class="token operator">></span><span class="token punctuation">(</span>formData<span class="token operator">:</span> <span class="token constant">T</span><span class="token punctuation">,</span> rules<span class="token operator">:</span> Rules<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">type</span> <span class="token class-name">Errors</span> <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token punctuation">[</span>k <span class="token keyword">in</span> <span class="token keyword">keyof</span> <span class="token constant">T</span><span class="token punctuation">]</span><span class="token operator">?</span><span class="token operator">:</span><span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span>
  <span class="token punctuation">}</span>
  <span class="token keyword">const</span> errors<span class="token operator">:</span>Errors <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>

  <span class="token comment">// 遍历 rules , 分析出错情况, 最终返回 errors</span>
  rules<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span>rule <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> <span class="token punctuation">{</span> key<span class="token punctuation">,</span> message<span class="token punctuation">,</span> pattern<span class="token punctuation">,</span> required <span class="token punctuation">}</span> <span class="token operator">=</span> rule
    <span class="token keyword">const</span> value <span class="token operator">=</span> formData<span class="token punctuation">[</span>key<span class="token punctuation">]</span>
    <span class="token comment">// 校验</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>required <span class="token operator">===</span> <span class="token boolean">true</span> <span class="token operator">&amp;&amp;</span> <span class="token operator">!</span>value<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      errors<span class="token punctuation">[</span>key<span class="token punctuation">]</span> <span class="token operator">=</span> errors<span class="token punctuation">[</span>key<span class="token punctuation">]</span> <span class="token operator">??</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
          errors<span class="token punctuation">[</span>key<span class="token punctuation">]</span><span class="token operator">?.</span><span class="token function">push</span><span class="token punctuation">(</span>message<span class="token punctuation">)</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>pattern <span class="token operator">&amp;&amp;</span> value <span class="token operator">&amp;&amp;</span> <span class="token operator">!</span>pattern<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>value<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      errors<span class="token punctuation">[</span>key<span class="token punctuation">]</span> <span class="token operator">=</span> errors<span class="token punctuation">[</span>key<span class="token punctuation">]</span> <span class="token operator">??</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
      errors<span class="token punctuation">[</span>key<span class="token punctuation">]</span><span class="token operator">?.</span><span class="token function">push</span><span class="token punctuation">(</span>message<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
  <span class="token keyword">return</span> errors
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br></div></div><h3 id="使用校验函数并渲染模板" tabindex="-1"><a class="header-anchor" href="#使用校验函数并渲染模板" aria-hidden="true">#</a> 使用校验函数并渲染模板</h3>
<p><strong>点击确定</strong>时触发此校验函数</p>
<div class="language-vue ext-vue line-numbers-mode"><pre v-pre class="language-vue"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript">
<span class="token comment">// 表单数据</span>
<span class="token keyword">const</span> formData <span class="token operator">=</span> <span class="token function">reactive</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">tagName</span><span class="token operator">:</span> <span class="token string">''</span><span class="token punctuation">,</span>
  <span class="token literal-property property">emoji</span><span class="token operator">:</span><span class="token string">''</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token comment">// 表单数据 ts 类型</span>
type FormData <span class="token operator">=</span>  <span class="token punctuation">{</span>
  <span class="token literal-property property">tagName</span><span class="token operator">:</span>string
  <span class="token literal-property property">emoji</span><span class="token operator">:</span>string
<span class="token punctuation">}</span>
<span class="token comment">// 校验规则</span>
<span class="token keyword">const</span> <span class="token literal-property property">rules</span><span class="token operator">:</span>Rules<span class="token operator">&lt;</span>FormData<span class="token operator">></span> <span class="token operator">=</span> <span class="token punctuation">[</span>
  <span class="token punctuation">{</span> <span class="token literal-property property">key</span><span class="token operator">:</span> <span class="token string">'tagName'</span><span class="token punctuation">,</span> <span class="token literal-property property">required</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token literal-property property">message</span><span class="token operator">:</span> <span class="token string">'必填'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span> <span class="token literal-property property">key</span><span class="token operator">:</span> <span class="token string">'tagName'</span><span class="token punctuation">,</span> <span class="token literal-property property">pattern</span><span class="token operator">:</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^.{1,4}$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">,</span> <span class="token literal-property property">message</span><span class="token operator">:</span> <span class="token string">'请填入1~4个字符'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span> <span class="token literal-property property">key</span><span class="token operator">:</span> <span class="token string">'emoji'</span><span class="token punctuation">,</span> <span class="token literal-property property">required</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token literal-property property">message</span><span class="token operator">:</span> <span class="token string">'必填'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
<span class="token comment">// 最终错误结果</span>
<span class="token keyword">const</span> errors <span class="token operator">=</span> ref<span class="token operator">&lt;</span>any<span class="token operator">></span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token comment">// 点击时 触发</span>
<span class="token keyword">const</span> <span class="token function-variable function">onSubmit</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">e</span><span class="token operator">:</span>Event</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token comment">// 取消默认动作</span>
  e<span class="token punctuation">.</span><span class="token function">preventDefault</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
  errors<span class="token punctuation">.</span>value <span class="token operator">=</span> validate<span class="token operator">&lt;</span>FormData<span class="token operator">></span><span class="token punctuation">(</span>formData<span class="token punctuation">,</span> rules<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br></div></div><p><img src="@source/.vuepress/public/images/errors1.png" alt="图片"></p>
<p>并且在模板上绑定进行渲染
<img src="@source/.vuepress/public/images/errors2.png" alt="图片"></p>
</template>
