<template><h1 id="各种优化" tabindex="-1"><a class="header-anchor" href="#各种优化" aria-hidden="true">#</a> 各种优化</h1>
<h2 id="修复动画切换时渲染错误" tabindex="-1"><a class="header-anchor" href="#修复动画切换时渲染错误" aria-hidden="true">#</a> 修复动画切换时渲染错误</h2>
<p>使用<code>Transition</code>的过渡模式 <code>mode</code> , 先出后进</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>Transition</span> <span class="token attr-name">mode</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>out-in<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  ...
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>Transition</span><span class="token punctuation">></span></span> 
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h2 id="iconpark-图标" tabindex="-1"><a class="header-anchor" href="#iconpark-图标" aria-hidden="true">#</a> IconPark 图标</h2>
<p><a href="https://iconpark.oceanengine.com/official" target="_blank" rel="noopener noreferrer">图标库<ExternalLinkIcon/></a>,<a href="https://www.npmjs.com/package/@icon-park/vue-next" target="_blank" rel="noopener noreferrer">Vue3版本的安装<ExternalLinkIcon/></a></p>
<p>老方法导入</p>
<p>plugins/iconpark/index.ts</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span>App<span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'vue'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span>install<span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@icon-park/vue-next/es/all'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token string">'@icon-park/vue-next/styles/index.css'</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">setupIconPark</span><span class="token punctuation">(</span>app<span class="token operator">:</span>App<span class="token punctuation">)</span><span class="token punctuation">{</span>
  <span class="token function">install</span><span class="token punctuation">(</span>app<span class="token punctuation">)</span>             
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>plugins/index.ts</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span>App<span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'vue'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span>setupTailwindcss<span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@/plugins/tailwindcss'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> _ <span class="token keyword">from</span> <span class="token string">'lodash'</span>
<span class="token keyword">import</span> setupElementPlus <span class="token keyword">from</span> <span class="token string">'@/plugins/elementui'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> setupPinia <span class="token keyword">from</span> <span class="token string">'@/plugins/store'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span>setupIconPark<span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@/plugins/iconpark'</span><span class="token punctuation">;</span>
<span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">setupPlugins</span><span class="token punctuation">(</span>app<span class="token operator">:</span>App<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token function">setupTailwindcss</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
  <span class="token function">setupElementPlus</span><span class="token punctuation">(</span>app<span class="token punctuation">)</span>
  <span class="token function">autoRegisterComponent</span><span class="token punctuation">(</span>app<span class="token punctuation">)</span>
  <span class="token function">setupPinia</span><span class="token punctuation">(</span>app<span class="token punctuation">)</span>
  <span class="token function">setupIconPark</span><span class="token punctuation">(</span>app<span class="token punctuation">)</span>
<span class="token punctuation">}</span>

</code></pre><div class="highlight-lines"><br><br><br><br><br><br><br><br><br><br><br><div class="highlight-line">&nbsp;</div><br><br></div><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><h2 id="优化路由守卫" tabindex="-1"><a class="header-anchor" href="#优化路由守卫" aria-hidden="true">#</a> 优化路由守卫</h2>
<p>router/guard.ts</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span>RouteLocationNormalized<span class="token punctuation">,</span> Router<span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'vue-router'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> store<span class="token punctuation">,</span> <span class="token punctuation">{</span>IData<span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@/utils/store'</span><span class="token punctuation">;</span>

<span class="token keyword">import</span> <span class="token punctuation">{</span>CacheEnum<span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@/enum/cacheEnum'</span><span class="token punctuation">;</span>

<span class="token keyword">class</span> <span class="token class-name">Guard</span> <span class="token punctuation">{</span>
  <span class="token keyword">private</span> router<span class="token operator">:</span> Router<span class="token punctuation">;</span>

  <span class="token function">constructor</span><span class="token punctuation">(</span>router<span class="token operator">:</span> Router<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>router <span class="token operator">=</span> router<span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

  <span class="token keyword">public</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>router<span class="token punctuation">.</span><span class="token function">beforeEach</span><span class="token punctuation">(</span><span class="token punctuation">(</span>to<span class="token operator">:</span> RouteLocationNormalized<span class="token punctuation">,</span> from<span class="token operator">:</span> RouteLocationNormalized<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token keyword">if</span><span class="token punctuation">(</span>to<span class="token punctuation">.</span>meta<span class="token punctuation">.</span>auth <span class="token operator">&amp;&amp;</span> <span class="token operator">!</span><span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">token</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">return</span> <span class="token punctuation">{</span>name<span class="token operator">:</span><span class="token string">'login'</span><span class="token punctuation">}</span>
      <span class="token keyword">if</span><span class="token punctuation">(</span>to<span class="token punctuation">.</span>meta<span class="token punctuation">.</span>guest <span class="token operator">&amp;&amp;</span> <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">token</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">return</span> from
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token comment">//获取token</span>
  <span class="token keyword">private</span> <span class="token function">token</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> IData <span class="token operator">|</span> <span class="token keyword">null</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> store<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>CacheEnum<span class="token punctuation">.</span><span class="token constant">TOKEN_NAME</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">(</span>router<span class="token operator">:</span> Router<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">new</span> <span class="token class-name">Guard</span><span class="token punctuation">(</span>router<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">run</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="highlight-lines"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><br><br><br><br><br><br><br><br><br><br><br></div><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br></div></div></template>
